#!/bin/bash

# lxdfile

set -veufo pipefail

# ***** ****** *****
# *****  VARS  *****

name="graftest"

bash_scripts=( "setup-container.sh" "install-grafana.sh" "install-influxdb.sh" )

profiles="-p default"

confs=""

dist="ubuntu:16.04"



# ***** ********** *****
# *****  creation  *****

# create new lxd container
lxc launch $dist $name $profiles $confs

# wait a seconds to network and cloudinit
sleep 5

# upload and run each script
for script in ${bash_scripts[@]}
do
	printf "\n\nProcessing: $script\n"
	lxc file push $script $name/root/
	lxc exec $name -- /bin/bash /root/$script
done


exit 0

